// vite-vue/src/views/Home.vue
<script lang="ts">
import { Vue, Options } from "vue-class-component"
import Layout from "../layouts/Layout.vue"
@Options({
  components: {
    Layout
  }
})
export default class App extends Vue {
  count = 0
  mounted() {
    const interval = setInterval(() => this.count++, 1000)
    return () => {
      clearInterval(interval)
    }
  }
}
</script>

<template>
  <Layout>
    <main class="main">
      <img src="/logo.svg" class="main__logo" alt="logo" />
      <p>
        Page has been open for <code>{{ count }}</code> seconds.
      </p>
    </main>
  </Layout>
</template>

<style lang="scss">
@keyframes logo-pulse {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(1.06);
  }
}

.main {
  background-color: #f9f6f6;
  color: #333;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  &__logo {
    height: 36vmin;
    pointer-events: none;
    margin-bottom: 3rem;
    animation: logo-pulse infinite 1.6s ease-in-out alternate;
  }
}
</style>

// vite-svelte/src/routes/Home.svelte
<script lang="ts">
  import logo from "../assets/logo.svg"
  import {onMount} from "svelte"

  let count = 0
  onMount(() => {
    const interval = setInterval(() => count++, 1000)
    return () => {
      clearInterval(interval)
    }
  })
</script>

<style lang="scss" scoped>
  @keyframes App-logo-pulse {
    from {
      transform: scale(1);
    }
    to {
      transform: scale(1.06);
    }
  }

  .home {
    background-color: #f9f6f6;
    color: #333;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: calc(10px + 2vmin);
  }

  .logo {
    height: 36vmin;
    pointer-events: none;
    margin: 2rem 0 3rem 0;
    animation: App-logo-pulse infinite 1.6s ease-in-out alternate;
  }
</style>

<div class="home">
  <h1>Home</h1>
  <img src="{logo}" class="logo" alt="logo" />
  <p>Page has been open for <code>{count}</code> seconds.</p>
  <a class="App-link" href="https://svelte.dev" target="_blank" rel="noopener noreferrer">
    Learn Svelte
  </a>
</div>
