// lit/src/lit-navbar.ts
import { html, css, LitElement } from "lit";
import { customElement } from "lit/decorators.js";

/**
 * A generic header element.
 *
 * @slot - This element has a slot
 */
@customElement("my-navbar")
export class MyNavbar extends LitElement {
  static styles = css`
    nav {
      width: 100vw;
      padding: 1rem 0rem;
      font-weight: 600;
      color: var(--gray-000);
      text-align: center;
      background-color: var(--accent);
    }

    ul {
      display: flex;
      justify-content: center;
      padding: 0;
      margin: 0;
      list-style: none;
    }
  `;

  render() {
    return html`
      <nav class="nav">
        <ul>
          <slot>
        </ul>
      </nav>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "my-navbar": MyNavbar;
  }
}

// snowpack-svelte/src/lib/Navbar.svelte
<style lang="scss">
  nav {
    background-color: var(--red);
    display: grid;
    font-weight: 600;
    padding: 1rem 2rem;
    place-items: center;
    text-align: center;
    width: 100%;
  }

  nav a {
    color: var(--grey-000);
    text-decoration: none;
  }

  nav a:hover {
    text-decoration: underline;
  }

  ul {
    display: flex;
    list-style: none;
    margin: 0;
    padding: 0;
  }

  ul li {
    padding: 0 2rem;
  }
</style>

<nav class="nav">
  <ul>
    <a href="/"><li>Home</li></a>
    <a href="/counter"><li>Counter</li></a>
    <a href="/about"><li>About</li></a>
  </ul>
</nav>
