// svelte-kit/src/lib/Footer.svelte
<script lang="ts">
  const year = new Date().getFullYear();
</script>

<footer>
  <p>&copy; {year}</p>
</footer>

<!-- prettier-ignore -->
<style lang="scss">
  footer {
    width: 100vw;
    padding: 2rem 0;
    color: var(--grey-800);
    text-align: center;
    border-top: 1px solid var(--red);
  }
</style>

// snowpack-vue/src/components/Footer.vue
<script lang="ts">
import { Vue, Options } from "vue-property-decorator"

@Options({
  name: "Footer"
})
export default class Footer extends Vue {
  year = new Date().getFullYear()
}
</script>

<template>
  <footer>
    <p>&copy; {{ year }}</p>
  </footer>
</template>

<!-- prettier-ignore -->
<style lang="scss">
footer {
  border-top: 1px solid var(--dark-green);
  color: var(--dark-green);
  padding: 2rem 0;
  text-align: center;
  width: 100vw;
}
</style>
