// lit/src/lit-footer.ts
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

/**
 * A generic footer with the curren year.
 *
 * @slot - This element has a slot
 * @csspart button - The button
 */
@customElement("my-footer")
export class MyFooter extends LitElement {
  static styles = css`
    footer {
      width: 100vw;
      padding: 0.7rem 0;
      color: var(--accent);
      text-align: center;
      border-top: 2px solid var(--accent);
    }
  `;

  /**
   * The current year
   */
  @property()
  year = new Date().getFullYear();

  render() {
    return html`
      <footer>
        <p><strong>&copy; ${this.year}</strong></p>
      </footer>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "my-footer": MyFooter;
  }
}

// snowpack-vue/src/components/Footer.vue
<script lang="ts">
import { Vue, Options } from "vue-property-decorator"

@Options({
  name: "Footer"
})
export default class Footer extends Vue {
  year = new Date().getFullYear()
}
</script>

<template>
  <footer>
    <p>&copy; {{ year }}</p>
  </footer>
</template>

<!-- prettier-ignore -->
<style lang="scss">
footer {
  border-top: 1px solid var(--dark-green);
  color: var(--dark-green);
  padding: 2rem 0;
  text-align: center;
  width: 100vw;
}
</style>
