// vite-react/src/components/Layout.tsx
import React, { FC } from "react"

import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import "@/styles/layout.scss"

interface Props {
  children: React.ReactNode
}

const Layout: FC<Props> = ({ children }) => {
  return (
    <div className="parent">
      <div>
        <Header />
        <Navbar />
      </div>
      <div>
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  )
}

export default Layout

// snowpack-vue/src/layouts/Layout.vue
<template>
  <div class="layout">
    <Header />
    <Nav />
    <slot />
    <Footer />
  </div>
</template>

<script lang="ts">
import { Vue, Options } from "vue-class-component"
import Footer from "../components/Footer.vue"
import Header from "../components/Header.vue"
import Navbar from "../components/Navbar.vue"

@Options ({
  name: "Layout",
  components: {
    Footer,
    Header,
    Navbar
  }
})
export default class Layout extends Vue {}
</script>
