// vite-vue/src/App.vue
<script lang="ts">import { Vue, Options } from "vue-class-component"
import Footer from "./components/Footer.vue"
import Header from "./components/Header.vue"
import Navbar from "./components/Navbar.vue"

@Options({
  name: "App",
  components: {
    Footer,
    Header,
    // Layout,
    Navbar
  }
})
export default class App extends Vue {

}
</script>

<template>
  <div id="app">
    <div>
      <Header />
      <Navbar />
    </div>
    <main>
      <router-view />
    </main>
    <Footer />
  </div>
</template>

<!-- prettier-ignore -->
<style lang="scss">
#app {
  display: grid;
  grid-template-rows: auto 1fr auto;
  height: 100vh;
  place-items: center;
}
</style>

// snowpack-svelte/src/App.svelte
<script lang="ts">
  import {onMount} from "svelte"
  import { Router, Route } from "svelte-routing";

  import Home from "./pages/Home.svelte"
  // import Footer from "./components/Footer.svelte"
  // import Header from "./components/Header.svelte"
  // import Navbar from "./components/Navbar.svelte"
  let count = 0
  onMount(() => {
    const interval = setInterval(() => count++, 1000)
    return () => {
      clearInterval(interval)
    }
  })
</script>

<style lang="scss">
  .app {
    display: grid;
    grid-template-rows: auto 1fr auto;
    height: 100vh;
    place-items: center;
  }
</style>


<div class="app">
  <Router>
  <div>
<!--     <Header /> -->
<!--     <Navbar /> -->
  </div>
  <main>
    <Route path="/home" component="{Home}" />
    <Home />
  </main>
<!--   <Footer /> -->
  </Router>
</div>
