// snowpack-vue/src/layouts/Layout.vue
<template>
  <div class="layout">
    <Header />
    <Nav />
    <slot />
    <Footer />
  </div>
</template>

<script lang="ts">
import { Vue, Options } from "vue-class-component"
import Footer from "../components/Footer.vue"
import Header from "../components/Header.vue"
import Navbar from "../components/Navbar.vue"

@Options ({
  name: "Layout",
  components: {
    Footer,
    Header,
    Navbar
  }
})
export default class Layout extends Vue {}
</script>

// react-routes/src/components/Layout.tsx
import { FC, ReactNode } from "react"
import { Header } from "components/Header"
import { Footer } from "components/Footer"
import { Navbar } from "components/Navbar"

interface Props {
  children: ReactNode
}

export const Layout: FC<Props> = ({ children }) => {
  return (
    <div className="parent">
      <div>
        <Header />
        <Navbar />
      </div>
      <div>
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  )
}
