// svelte-kit/src/routes/__layout.svelte
<script lang="ts">
  import Footer from "$lib/Footer.svelte";
  import Header from "$lib/Header.svelte";
  import Navbar from "$lib/Navbar.svelte";
  import "sanitize.css/sanitize.css";
  import "sanitize.css/assets.css";
  import "sanitize.css/reduce-motion.css";
  import "sanitize.css/typography.css";
  import "../styles/app.scss";
</script>

<div>
  <Header />
  <Navbar />
</div>
<main>
  <slot />
</main>
<Footer />

// react-routes/src/components/Layout.tsx
import { FC, ReactNode } from "react"
import { Header } from "components/Header"
import { Footer } from "./Footer"
import { Navbar } from "./Navbar"
import "styles/layout.scss"

interface Props {
  children: ReactNode
}

export const Layout: FC<Props> = ({ children }) => {
  return (
    <div className="parent">
      <div>
        <Header />
        <Navbar />
      </div>
      <div>
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  )
}
