// vite-vue/src/views/Home.vue
<script lang="ts">
import { Vue, Options, Prop } from "vue-property-decorator"

@Options({
  name: "Home"
})
export default class Home extends Vue {
  count = 0
  @Prop(String) readonly title: string | undefined
  mounted() {
    const interval = setInterval(() => this.count++, 1000)
    return () => {
      clearInterval(interval)
    }
  }
}
</script>

<template>
  <div :class="title">
    <h1>{{ title[0].toUpperCase() + title.slice(1, title.length) }}</h1>
    <img src="@/assets/logo.svg" class="logo" alt="logo" />
    <p>
      Page has been open for <code>{{ count }}</code> seconds.
    </p>
  </div>
</template>

<!-- prettier-ignore -->
<style lang="scss" scoped>
@keyframes logo-pulse {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(1.06);
  }
}

.home {
  margin: 5rem 0;
  text-align: center;
  p {
    margin: 0.4rem;
  }
}

.logo {
  height: 36vmin;
  margin: 3rem;
  pointer-events: none;
  @media (prefers-reduced-motion: no-preference) {
    animation: logo-pulse infinite 1.6s ease-in-out alternate;
  }
}
</style>

// svelte-vite/src/routes/Home.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import logo from "@/assets/logo.svg";

  let count = 0;
  onMount(() => {
    const interval = setInterval(() => count++, 1000);
    return () => {
      clearInterval(interval);
    };
  });
</script>

<div class="home">
  <h1>Home</h1>
  <img src={logo} class="logo" alt="logo" />
  <p>Page has been open for <code>{count}</code> seconds.</p>
  <a
    class="App-link"
    href="https://svelte.dev"
    target="_blank"
    rel="noopener noreferrer"
  >
    Learn Svelte
  </a>
</div>

<!-- prettier-ignore -->
<style lang="scss">
  @keyframes logo-pulse {
    from {
      transform: scale(1);
    }
    to {
      transform: scale(1.06);
    }
  }

  .home {
    margin: 5rem 0;
    text-align: center;
    p {
      margin: 0.4rem;
    }
  }

  .logo {
    height: 36vmin;
    margin: 3rem;
    pointer-events: none;
    display: inline;
    @media (prefers-reduced-motion: no-preference) {
      animation: logo-pulse infinite 1.6s ease-in-out alternate;
    }
  }
</style>
