// snowpack-vue/src/views/404.vue
<script lang="ts">
import { Vue, Options } from "vue-property-decorator"

@Options({
  name: "NotFound"
})
export default class NotFound extends Vue {}
</script>

<template>
  <div class="four-oh-four">
    <h1>404 Not Found</h1>
    <p>
      You've hit a path that does not exist,
      <br />
      oh the sadness!
    </p>
    <router-link :to="{ name: 'home' }">Home</router-link>
  </div>
</template>

<style lang="scss" scoped>
.four-oh-four {
  margin: 5rem 2rem;
}
</style>

// snowpack-react/src/pages/404.tsx
import React, { FC } from "react"
import { Link } from "@reach/router";
import type { RouteComponentProps } from "@reach/router"

import styles from "@/styles/404.module.scss"

import Layout from "@/components/Layout"

const NotFound: FC<RouteComponentProps> = () => {
  return (
    <Layout>
      <div className={styles["four-oh-four"]}>
        <h1>404 Not Found</h1>
        <p>
          You&apos;ve hit a path that does not exist,
          <br />
          oh the sadness!
        </p>
        <Link to="/">Home</Link>
      </div>
    </Layout>
  )
}

export default NotFound
