// vite-vue/src/views/404.vue
<script lang="ts">
import { Vue, Options } from "vue-property-decorator"

@Options({
  name: "NotFound"
})
export default class NotFound extends Vue {}
</script>

<template>
  <div class="four-oh-four">
    <h1>404 Not Found</h1>
    <p>
      You've hit a path that does not exist,
      <br />
      oh the sadness!
    </p>
    <router-link :to="{ name: 'home' }">Home</router-link>
  </div>
</template>

<!-- prettier-ignore -->
<style lang="scss" scoped>
.four-oh-four {
  margin: 5rem 2rem;
}
</style>

// snowpack-svelte/src/routes/404.svelte
<script lang="ts">
  import { link } from "svelte-routing"
</script>

<div class="four-oh-four">
  <h1>404 Not Found</h1>
  <p>
    You've hit a path that does not exist,
    <br />
    oh the sadness!
  </p>
  <a href="/" use:link>Home</a>
</div>

<!-- prettier-ignore -->
<style lang="scss">
  .four-oh-four {
    margin: 5rem 2rem;
  }
</style>
