// snowpack-vue/src/views/Home.vue
<script lang="ts">
import { Vue, Options } from "vue-class-component"
// import { capitalize } from "../lib/utils"

@Options({
  name: "Home"
})
export default class Home extends Vue {
  title = "home"
  count = 0
  mounted() {
    const interval = setInterval(() => this.count++, 1000)
    return () => {
      clearInterval(interval)
    }
  }
  // @Prop(String) readonly title: string | undefined
}
</script>

<template>
  <div :class="title">
    <h1>{{ title[0].toUpperCase() + title.slice(1, title.length) }}</h1>
    <img src="/logo.svg" class="app-logo" alt="logo" />
    <p>
      Page has been open for <code>{{ count }}</code> seconds.
    </p>
  </div>
</template>

<style lang="scss">
@keyframes logo-pulse {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(1.06);
  }
}

.home {
  margin: 5rem 0;
  text-align: center;
  p {
    margin: 0.4rem;
  }
}

.app-logo {
  height: 36vmin;
  pointer-events: none;
  margin: 3rem;
  @media (prefers-reduced-motion: no-preference) {
    animation: logo-pulse infinite 1.6s ease-in-out alternate;
  }
}
</style>

// snowpack-svelte/src/routes/Home.svelte
<script lang="ts">
  import logo from "../assets/logo.svg"
  import {onMount} from "svelte"

  let count = 0
  onMount(() => {
    const interval = setInterval(() => count++, 1000)
    return () => {
      clearInterval(interval)
    }
  })
</script>

<style lang="scss" scoped>
  @keyframes logo-pulse {
    from {
      transform: scale(1);
    }
    to {
      transform: scale(1.06);
    }
  }

  .home {
    margin: 5rem 0;
    text-align: center;
    p {
      margin: 0.4rem;
    }
  }

  .logo {
    height: 36vmin;
    pointer-events: none;
    margin: 3rem;
    @media (prefers-reduced-motion: no-preference) {
      animation: logo-pulse infinite 1.6s ease-in-out alternate;
    }
  }
</style>

<div class="home">
  <h1>Home</h1>
  <img src="{logo}" class="logo" alt="logo" />
  <p>Page has been open for <code>{count}</code> seconds.</p>
  <a class="App-link" href="https://svelte.dev" target="_blank" rel="noopener noreferrer">
    Learn Svelte
  </a>
</div>
